# Generated by Django 5.0.6 on 2024-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='date',
            field=models.IntegerField(),
        ),
    ]
